apiVersion: v1
kind: Service
metadata:
  name: tpp
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
    cloud.google.com/backend-config: '{"default": "tpp-backendconfig"}'
spec:
  ports:
  - name: tpp
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: tpp
  type: ClusterIP
